# Generated by Django 4.2.2 on 2023-07-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_tags_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(blank=True, upload_to="posts/%Y/%m/%d/"),
        ),
    ]
